name: Daily Dashboard Update

on:
  schedule:
    - cron: '15 13 * * 1-5'  # 09:15 ET weekdays (13:15 UTC; adjust as needed)
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          OFFLINE: '0'
          START_DATE: '2018-01-01'
          CONTINUE_ON_FETCH_ERROR: '1'
          SKIP_FX: '0'
        run: |
          python scripts/run_pipeline.py
      - name: Commit artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add reports/figures reports/one_pagers README.md data/processed
          git commit -m "Automated update: $(date -u +"%Y-%m-%d")" || echo "No changes to commit"
          git push
